/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import Config.Conexion;
import static java.lang.System.out;
import java.security.SecureRandom;
import java.sql.*;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.ArrayList;
import javax.swing.ButtonModel;
import javax.swing.JOptionPane;
import modelo.bancoPregunta;
import modelo.pregunta;

/**
 *
 * @author cristian
 */
public class juego extends javax.swing.JFrame {

    /**
     * Creates new form juego
     */
    ArrayList<pregunta> bncpreg = new ArrayList<>();
    SecureRandom ale = new SecureRandom();
    int upRound = 1;
    pregunta aux = new pregunta();
    int valor;

    public juego() {
        JOptionPane.showMessageDialog(null,"bienvenido al juego ¿quien quiere ser sofkiano? \n tendra una pregunta y cuatro opciones de respuesta donde sólo una es la correcta\n cada 5 preguntas correctas aumenta la complejidad y el monto del premio\n muchos éxitos.....", "Bienvenida", JOptionPane.INFORMATION_MESSAGE);
        initComponents();
        level.setText(registro.round);
        premio.setText(registro.prem);
        bncpreg.add(bancoPregunta.n1);
        bncpreg.add(bancoPregunta.n2);
        bncpreg.add(bancoPregunta.n3);
        bncpreg.add(bancoPregunta.n4);
        bncpreg.add(bancoPregunta.n5);
        bncpreg.add(bancoPregunta.n6);
        bncpreg.add(bancoPregunta.n7);
        bncpreg.add(bancoPregunta.n8);
        bncpreg.add(bancoPregunta.n9);
        bncpreg.add(bancoPregunta.n10);
        bncpreg.add(bancoPregunta.n11);
        bncpreg.add(bancoPregunta.n12);
        bncpreg.add(bancoPregunta.n13);
        bncpreg.add(bancoPregunta.n14);
        bncpreg.add(bancoPregunta.n15);
        bncpreg.add(bancoPregunta.n16);
        bncpreg.add(bancoPregunta.n17);
        bncpreg.add(bancoPregunta.n18);
        bncpreg.add(bancoPregunta.n19);
        bncpreg.add(bancoPregunta.n20);
        bncpreg.add(bancoPregunta.n21);
        bncpreg.add(bancoPregunta.n22);
        bncpreg.add(bancoPregunta.n23);
        bncpreg.add(bancoPregunta.n24);
        bncpreg.add(bancoPregunta.n25);
        useName.setText(registro.nick);
        selectionQuestion();
        bncpreg.remove(valor);
        lblPregunta.setText("Pregunta " + upRound + " de 5");
    }

    public void selectionQuestion() {
        do {
            valor = ale.nextInt(bncpreg.size());
            aux = bncpreg.get(valor);

        } while (aux.getCategoria() != Integer.parseInt(level.getText()));

        jLabel4.setText(aux.getPregunta());
        opcA.setText(aux.getOpcionA());
        opcB.setText(aux.getOpcionB());
        opcC.setText(aux.getOpcionC());
        opcD.setText(aux.getOpcionD());

    }

    public void upPremio() {
        if (Integer.parseInt(level.getText()) == 1) {
            int pre = Integer.parseInt(premio.getText());
            pre = pre + 100;
            premio.setText(String.valueOf(pre));
        } else if (Integer.parseInt(level.getText()) == 2) {
            int pre = Integer.parseInt(premio.getText());
            pre = pre + 300;
            premio.setText(String.valueOf(pre));
        } else if (Integer.parseInt(level.getText()) == 3) {
            int pre = Integer.parseInt(premio.getText());
            pre = pre + 500;
            premio.setText(String.valueOf(pre));
        } else if (Integer.parseInt(level.getText()) == 4) {
            int pre = Integer.parseInt(premio.getText());
            pre = pre + 700;
            premio.setText(String.valueOf(pre));
        } else if (Integer.parseInt(level.getText()) == 5) {
            int pre = Integer.parseInt(premio.getText());
            pre = pre + 1000;
            premio.setText(String.valueOf(pre));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        opcResp = new javax.swing.ButtonGroup();
        useName = new javax.swing.JLabel();
        level = new javax.swing.JLabel();
        premio = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        opcA = new javax.swing.JRadioButton();
        opcB = new javax.swing.JRadioButton();
        opcC = new javax.swing.JRadioButton();
        opcD = new javax.swing.JRadioButton();
        btnConf = new javax.swing.JButton();
        lblPregunta = new javax.swing.JLabel();
        btnSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        useName.setText("jLabel1");

        level.setText("jLabel1");

        premio.setText("jLabel1");

        jLabel1.setText("Usuario:");

        jLabel2.setText("Ronda:");

        jLabel3.setText("Premio:");

        jLabel4.setText("pregunta");

        opcResp.add(opcA);
        opcA.setText("jRadioButton1");

        opcResp.add(opcB);
        opcB.setText("jRadioButton1");

        opcResp.add(opcC);
        opcC.setText("jRadioButton1");

        opcResp.add(opcD);
        opcD.setText("jRadioButton2");

        btnConf.setText("Responder");
        btnConf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfActionPerformed(evt);
            }
        });

        lblPregunta.setText("jLabel5");

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblPregunta)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(28, 28, 28)
                                .addComponent(useName)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 94, Short.MAX_VALUE)
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(level)
                                .addGap(128, 128, 128)
                                .addComponent(jLabel3)
                                .addGap(39, 39, 39)
                                .addComponent(premio)))
                        .addGap(70, 70, 70))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(opcA)
                                .addGap(80, 80, 80)
                                .addComponent(opcB))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnSalir)
                                    .addComponent(opcC))
                                .addGap(80, 80, 80)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(opcD, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnConf, javax.swing.GroupLayout.Alignment.TRAILING))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(useName)
                    .addComponent(level)
                    .addComponent(premio)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPregunta))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(opcA)
                    .addComponent(opcB))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(opcC)
                    .addComponent(opcD))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConf)
                    .addComponent(btnSalir))
                .addContainerGap(91, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfActionPerformed
        // TODO add your handling code here:
        int ronda = Integer.parseInt(level.getText());
        int premioAcum = Integer.parseInt(premio.getText());

        String resp = opcA.isSelected() ? opcA.getText() : opcB.isSelected() ? opcB.getText() : opcC.isSelected() ? opcC.getText() : opcD.isSelected() ? opcD.getText() : "";

        if ("".equals(resp)) {
            JOptionPane.showMessageDialog(null, "no ha seleccionado ninguna respuesta", "Error", JOptionPane.ERROR_MESSAGE);
        } else if (resp.equals(aux.getOpcionTrue())) {
            JOptionPane.showMessageDialog(null, "Respuesta correcta", "Muy bien", JOptionPane.INFORMATION_MESSAGE);
            upPremio();
            upRound++;
            if (upRound > 5) {
                JOptionPane.showMessageDialog(null,"ha subido al siguiente nivel de preguntas", "subir nivel", JOptionPane.INFORMATION_MESSAGE);
                level.setText(String.valueOf(ronda + 1));
                upRound = 1;
            }
            if (!bncpreg.isEmpty()) {
                selectionQuestion();
                bncpreg.remove(valor);
                lblPregunta.setText("Pregunta " + upRound + " de 5");
                opcResp.clearSelection();
            } else {
                JOptionPane.showMessageDialog(null,"felicidades has ganado", "felicitaciones", JOptionPane.INFORMATION_MESSAGE);
                System.out.println("Ha ganado");
                Conexion con = new Conexion();
            Connection cn;
            PreparedStatement ps;
            ResultSet rs;
            
        String sql="Update jugador SET ronda='"+1+"',premio='"+premio.getText()+"' Where nickname='"+useName.getText()+"'"; 
        try {
                        cn = con.getConnection();
                        ps = cn.prepareStatement(sql);
                        ps.executeUpdate();

                    } catch (Exception e) {
                        out.print(e.getMessage());
                    }
                System.exit(0);
            }

        } else {
            //Perdió y se sale
            
            JOptionPane.showMessageDialog(null, "respuesta incorrecta", "Perdio", JOptionPane.ERROR_MESSAGE);
            Conexion con = new Conexion();
            Connection cn;
            PreparedStatement ps;
            ResultSet rs;
            
        String sql="Update jugador SET ronda='"+1+"',premio='"+0+"' Where nickname='"+useName.getText()+"'"; 
        try {
                        cn = con.getConnection();
                        ps = cn.prepareStatement(sql);
                        ps.executeUpdate();

                    } catch (Exception e) {
                        out.print(e.getMessage());
                    }
            System.exit(0);
            
        }


    }//GEN-LAST:event_btnConfActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null,"va a salirse del juego y en el proximo intento continua en la ronda que quedó", "Salirse del juego", JOptionPane.WARNING_MESSAGE);
          Conexion con = new Conexion();
            Connection cn;
            PreparedStatement ps;
            ResultSet rs;
            
        String sql="Update jugador SET ronda='"+level.getText()+"',premio='"+premio.getText()+"' Where nickname='"+useName.getText()+"'"; 
        try {
                        cn = con.getConnection();
                        ps = cn.prepareStatement(sql);
                        ps.executeUpdate();

                    } catch (Exception e) {
                        out.print(e.getMessage());
                    }
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new juego().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConf;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblPregunta;
    private javax.swing.JLabel level;
    private javax.swing.JRadioButton opcA;
    private javax.swing.JRadioButton opcB;
    private javax.swing.JRadioButton opcC;
    private javax.swing.JRadioButton opcD;
    private javax.swing.ButtonGroup opcResp;
    private javax.swing.JLabel premio;
    private javax.swing.JLabel useName;
    // End of variables declaration//GEN-END:variables
}
